services:
  postgres:
    image: postgres:18.6
    container_name: postgres-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: pndbexercise
      POSTGRES_USER: mhmdskrh
      POSTGRES_PASSWORD: password_123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myappuser -d myappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    name: myapp_postgres_data
